FROM ubuntu:16.04

RUN  apt-get update

RUN apt-get install sudo -y

RUN apt-get install software-properties-common -y

RUN  apt-get install maven -y

RUN echo mvn -version

# Install Java
RUN apt-get install default-jdk -y

